### ISSUE TITLE
Here you can report any bugs and glitches you have found!

### ISSUE THREAD

**Issue by ULTUX** [ULTUX/StoneDropPlugin#10]

**Comment by kuba4400** [comment]
Problem jest nastepujacy. Jak wywalilem opcje z customowa nazwa diamentu to ona ciagle sie tam pojawia!
Jak zmienilem customowa nazwe dla dropu diamentu to jest okey, zmienila sie. Ale jak chce wywalic ja calkowicie to wciaz wypada diament z nazwa "Custom named diamond that is ..." a w configu nic takiego nie mam.
Chce zeby diamenty wypadaly bez customowej nazwy, poniewaz niektore pluginy maja problem w ich pozniejszej interpretacji.

  DIAMOND:
    fortune-0:
      chance: 0.025
      max-amount: 2
      min-amount: 1
    fortune-1:
      chance: 0.027
      max-amount: 3
      min-amount: 1
    fortune-2:
      chance: 0.03
      max-amount: 3
      min-amount: 2
    fortune-3:
      chance: 0.0325
      max-amount: 4
      min-amount: 3
      
Cos takiego mam w configu.
Probowalem z custom name ustawic na false czy '' ale nie podzialalo.
Tak samo usuniecie parametrow odpowiadajacych za wysokosc na ktorej mozna wydobyc diament po usunieciu takze pozostaja niezmienne.

**Comment by ULTUX** [comment]
Dodane do listy bugów, naprawie to w następnej aktualizacji. Dzięki za info

**Comment by deikiii** [comment]
Mam taki problem że plugin mi całkowicie nie działa mam wersje 1.15.2 niewiem czy to ja coś źle robie czy cokolwiek

**Comment by ULTUX** [comment]
> Mam taki problem że plugin mi całkowicie nie działa mam wersje 1.15.2 niewiem czy to ja coś źle robie czy cokolwiek

Proszę wyślij _logi_ - najlepiej odpal serwer i wyślij tutaj plik _latest.log_

**Comment by deikiii** [comment]
Dzieki za checi ale naprawiłem miłego tygodnia, :)

pon., 1 lut 2021, 01:39 użytkownik Władysław Nowak <notifications@github.com>
napisał:
