### ISSUE TITLE
Plugin doesn't start

### ISSUE THREAD

**Issue by xGlenor** [ULTUX/StoneDropPlugin#24]
Hi, I have a problem with running the plugin on the server
Server Version: 1.15.2 and 1.16.1
Type: PaperSpigot

org.bukkit.plugin.InvalidPluginException: Unsupported API version 1.16
	at org.bukkit.craftbukkit.v1_15_R1.util.CraftMagicNumbers.checkSupported(CraftMagicNumbers.java:276) ~[patched_1.15.2.jar:git-Paper-375]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:133) ~[patched_1.15.2.jar:git-Paper-375]
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:397) ~[patched_1.15.2.jar:git-Paper-375]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:305) ~[patched_1.15.2.jar:git-Paper-375]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.loadPlugins(CraftServer.java:360) ~[patched_1.15.2.jar:git-Paper-375]
	at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:234) ~[patched_1.15.2.jar:git-Paper-375]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:908) ~[patched_1.15.2.jar:git-Paper-375]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_265]

**Comment by ULTUX** [comment]
I will fix that ASAP.

**Comment by ULTUX** [comment]
I fixed your issued. If you would like to use the fixed plugin version, you can download it from here: **https://github.com/ULTUX/StoneDropPlugin/releases/tag/1.8.1**

Alternatively you can wait one day and download it from **bukkit.org** (it takes time for bukkit.org to upload verify the plugin).

**Comment by xGlenor** [comment]
Thank you :D 

I also have some suggestions :D
Could I write them in Polish?

**Comment by ULTUX** [comment]
Oczywiście, dawaj 😄

**Comment by xGlenor** [comment]
Po pierwsze dodałbym możliwość włączenia/ wyłączenia AutoUpdater, nie widzę tego w configu a myślę że jest to dość przydatna opcja, ponieważ przez ten właśnie wyżej błąd nie zauważyłem że serwer nie uruchomił pluginu co dopuściło do tego że gracze byli pozbawieni dropu przez kilka godzin :/ 

Kolejną sprawą jest dodanie opcji włączenia wyłączenia opcji z drop chestem :D Jest to zarąbista opcja, lecz nie wszyscy tego używają.

Nie wiem jak jest zrobiona opcja z komendami do końca co do /drop info, stack droppable, osobiście zrobiłbym tą funkcję na permisję, można fajnie potem przydzielać rozdzielać jakieś permisje po rangach itp. :D 

Kolejną sprawą jest Bug co do komendy /drop stack, podeślę tutaj filmik najlepiej :D 
https://www.youtube.com/watch?v=rCbfcRbrM-E Chodzi bardziej o koniec filmiku gdzie skopiowało itemki :/
Z tego co kojarzę to kumpel w konfiguracji znalazł błąd w instrukcji warunkowej :D 

to Chyba wszystko :D

**Comment by ULTUX** [comment]
Hmm ok, to może po kolei:
1. Auto updater: W folderze plugins masz folder Updater, w którym masz config, tam ustawiasz disabled: true, aby wyłączyć aktualizacje. Jeśli chcesz mogę dodatkowo dodać tą opcje w configu mojego pluginu.

2. Włączenie i wyłączenie drop chestu: wydaje mi się że najlepszym rozwiązaniem jest ustawienie `chest-spawn-chance: 0.0` w configu. Serwer może wyrzucić błąd jak ustawisz `0` zamiast `0.0`. Zostanie to naprawione w najbliższej aktualizacji 😀.

3. Permisje: dodam w następnej aktualizacji (dzięki za propozycje :D)

4. Bug: już naprawiony, dodam w zaraz w aktualizacji razem z resztą twoich propozycji

Dzięki za propozycje i zgłoszenie tych błędów. Jak masz jeszcze jakieś propozycje, pomysły lub błędy dotyczące tego pluginu to pisz :)

**Comment by ULTUX** [comment]
Właśnie opublikowałem nową wersję. [**Link**](https://github.com/ULTUX/StoneDropPlugin/releases/tag/1.8.2)

**Comment by ULTUX** [comment]
Niestety nie mam za bardzo czasu na jakieś bardziej szczegółowe szukanie błędów, wiec jeśli znajdziesz jakieś błędy w tej wersji to niezwłocznie daj mi znać, zanim zostanie to opublikowane na Bukkit.org.
Z góry dzięki!
