### ISSUE TITLE
Language support

### ISSUE THREAD

**Issue by ULTUX** [ULTUX/StoneDropPlugin#29]
Add config file to change messages.

**Comment by SrBedrock** [comment]
This would be very good especially to translate when a chest is found.

**Comment by ULTUX** [comment]
I've already implemented your feature in commits 0a55655c38f4cbfd0cadc7df9d01a85c3ef63d62 and d35ec2597fca8e0106cb9b31d8ba8b228dd76fc9. You can download the latest plugin version from [here](https://github.com/ULTUX/StoneDropPlugin/releases/tag/v1.9.2.1), also it will be available on Bukkit to download in a few days.
