### ISSUE TITLE
lang file don't work

### ISSUE THREAD

**Issue by jarek11223349** [ULTUX/StoneDropPlugin#60]
I translate plugin to Polish, but it's still English.
![image](https://user-images.githubusercontent.com/84684969/120025575-2a24a400-bff1-11eb-8c15-e9a49b224b4b.png)

![image](https://user-images.githubusercontent.com/84684969/120025595-33157580-bff1-11eb-9b21-1d0840eace26.png)

**Comment by ULTUX** [comment]
Try quoting the messages with double qoutes.
