### ISSUE TITLE
Items not dropping

### ISSUE THREAD

**Issue by cforeman97** [ULTUX/StoneDropPlugin#69]
Went through every plugin I have one by one, this seemed to be the source of the issue. When mining any ore, nothing will drop at all.

**Comment by ULTUX** [comment]
In config.yml enable ore drop and set ore drop chance to 1.0. 
In the upcomming update we will change default setting so that the ores drop items.

**Comment by cforeman97** [comment]
Such a simple and easy problem. Thank you for your fast response and effective solution :)

**Comment by ULTUX** [comment]
No problem 😃
