### ISSUE TITLE
Plugin Preventing normal drops

### ISSUE THREAD

**Issue by treygauche** [ULTUX/StoneDropPlugin#70]
i've been trying to update my spigot server to 1.17.1, and got everything up today, but when i tried to install the latest stonedrop, i'm finding that it 
a) does not drop the items i'm expecting
b) prevents drops from ore blocks (specifically iron and gold, since those are the ones that i've tried)

the other plugins i have are 
-advanced teleport 5.5.5
-CraftsPlus (latest)
-Dynmap 3.2-beta-2

is this a known bug, or is there something wrong with my setup?

thank you,
-timothy

**Comment by ULTUX** [comment]
a) Please send config.yml contents for testing
b) Duplicate of #69. Default plugin settings prevent drop from ores. Read the other issue for fix.

**Comment by treygauche** [comment]
i believe i have fixed it.  with the fix from #69, which solved the ore-drop issue, and then changing the 'realistic-drop' to false, i am now getting drops again.  thank you so much for the quick response!

**Comment by ULTUX** [comment]
Glad i could help. :)
